//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "usertokens")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub token_address: String,
    pub token_name: String,
    pub user_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
    #[sea_orm(has_many = "super::usertokenbalance::Entity")]
    Usertokenbalance,
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::usertokenbalance::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Usertokenbalance.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
